"""Streamlit chat UI. Run with: streamlit run app/streamlit_app.py (or ``make app``)."""

from __future__ import annotations

import streamlit as st

from challansaathi.llm import LLMUnavailableError
from challansaathi.pipeline import ChallanSaathi, source_to_dict
from challansaathi.sources import REGISTRY, known_states

AUTO = "Auto-detect from question"
CENTRAL_ONLY = "Central law only"
MAX_QUESTION_CHARS = 1000
EXAMPLES = [
    "What is the penalty for drunk driving?",
    "Haryana mein bus ki seating capacity ka rule kya hai?",
    "UP mein transport vehicle ke driver ka badge kaise milta hai?",
    "What does Section 129 of the Motor Vehicles Act say?",
]

st.set_page_config(page_title="ChallanSaathi", page_icon="⚖️", layout="centered")


@st.cache_resource(
    show_spinner="Loading the legal index and embedding model (the first run builds the "
    "index, about a minute)…"
)
def get_assistant() -> ChallanSaathi:
    return ChallanSaathi()


def render_sources(sources: list[dict]) -> None:
    st.markdown(f"**Sources ({len(sources)})**")
    for s in sources:
        pages = (
            f"p. {s['page_start']}"
            if s["page_start"] == s["page_end"]
            else f"pp. {s['page_start']}–{s['page_end']}"
        )
        label = f"[{s['source_id']}] {s['title']} — {s['unit'] if s['number'] else ''} "
        label += f"{s['number'] or s['heading'].split(':')[0]} ({pages})"
        with st.expander(label):
            if s["number"] and s["heading"]:
                st.markdown(f"**{s['heading']}**")
            central = s["jurisdiction"] == "Central"
            scope = "Central law" if central else f"{s['jurisdiction']} rules"
            st.caption(
                f"{scope} · {s['chapter'] or 'no chapter'} · {s['document']} {pages}"
                f" · text as of {s['text_as_of']}"
            )
            st.text(s["excerpt"] + ("…" if len(s["excerpt"]) >= 500 else ""))


with st.sidebar:
    st.title("⚖️ ChallanSaathi")
    st.write("Ask about Indian motor vehicle law in English, Hindi or Hinglish.")
    state_choice = st.selectbox("Jurisdiction", [AUTO, *known_states(), CENTRAL_ONLY])
    st.divider()
    st.markdown("**Documents searched**")
    for info in REGISTRY.values():
        st.caption(f"{info.title} — text as of {info.text_as_of}")
    st.warning(
        "The Motor Vehicles Act text predates the 2019 amendment, which raised most fines. "
        "Fine amounts shown may be outdated.",
        icon="⚠️",
    )
    st.caption(
        "**General information, not legal advice.** Answers are generated by a local LLM from "
        "the cited provisions and can contain mistakes — always check the source text."
    )
    if st.button("Clear chat", use_container_width=True):
        st.session_state.messages = []

try:
    assistant = get_assistant()
except Exception as exc:  # index build / model load failures are shown, not raised
    st.error(f"Could not start ChallanSaathi: {exc}")
    st.stop()

st.sidebar.caption(f"LLM: `{assistant.settings.ollama_model}` via Ollama")

if "messages" not in st.session_state:
    st.session_state.messages = []

if not st.session_state.messages:
    st.markdown("### Ask a question about motor vehicle law")
    st.caption("Try one of these:")
    for example in EXAMPLES:
        if st.button(example, use_container_width=True):
            st.session_state.pending = example
            st.rerun()

for message in st.session_state.messages:
    with st.chat_message(message["role"]):
        st.markdown(message["content"])
        if message.get("sources"):
            render_sources(message["sources"])

question = st.chat_input("e.g. What is the fine for driving without a licence?")
question = question or st.session_state.pop("pending", None)

if question:
    question = question.strip()[:MAX_QUESTION_CHARS]
    st.session_state.messages.append({"role": "user", "content": question})
    with st.chat_message("user"):
        st.markdown(question)

    state = {AUTO: None, CENTRAL_ONLY: "India"}.get(state_choice, state_choice)
    with st.chat_message("assistant"):
        with st.spinner("Searching the Acts and Rules…"):
            answer = assistant.ask(question, state=state)
        if answer.state == "India":
            st.caption("Searching central law only")
        elif answer.state:
            st.caption(f"Searching {answer.state} rules + central law")
        try:
            with st.spinner("Writing the answer…"):
                text = st.write_stream(answer.stream)
        except LLMUnavailableError as exc:
            text = f"⚠️ {exc}\n\nThe most relevant provisions found are listed below."
            st.warning(text)
        sources = [source_to_dict(r, i) for i, r in enumerate(answer.sources, start=1)]
        if sources:
            render_sources(sources)
    st.session_state.messages.append({"role": "assistant", "content": text, "sources": sources})
